name: RASP Configuration Version Control

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
    RASP-Configuration:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              ref: "main"

          - name: Upload RASP Configuration
            uses: actions/upload-artifact@v3
            with:
                name: RASP-Configurations
                path: rasp.json