name: Rasp Remove

on:
    issues:
      types:
        - closed

permissions: write-all

jobs:
    Remove-rasp-in-code:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout in main branch
          uses: actions/checkout@v4
          with:
            ref: "main"
            token: ${{ secrets.CLA_WRITE_ACCESS}}
        
        - name: Remove rasp module and configuration file from web server
          run: |
            
            git config user.name RKeertishKumar
            git config user.email 141417594+RKeertishKumar@users.noreply.github.com
            sed -i '9d' app.py
            sed -i '1d' app.py
            git diff
            git add .
            git commit -m "Removed RASP from web server."
            git push
            echo "# Removed RASP from web server." >> "$GITHUB_STEP_SUMMARY"

        
          